DROP TABLE IF EXISTS arrows CASCADE;
DROP TABLE IF EXISTS scores CASCADE;

DROP TABLE IF EXISTS sets CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS rounds CASCADE;

DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS teams CASCADE;

DROP TABLE IF EXISTS targets CASCADE;
DROP TABLE IF EXISTS status CASCADE;

DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;